const product = [
    {
        id: 1,
        name: "Nike Air Max Excee",
        productType: "running shoes",
        price: 50,
        rating: 4,
        image: "https://essential.vteximg.com.br/arquivos/ids/570144-1000-1000/316-0404_1.jpg?v=637907419578300000",
        description:"El Nike Air Max Excee, inspirado en el Nike Air Max 90, es una celebración de un clásico con una nueva óptica. Las líneas alargadas y las proporciones distorsionadas en la parte superior le dan un espacio nuevo y moderno al look de los años 90 que tanto te gusta.",
    },
    {
        id: 2,
        name: "Nike Ques 4",
        productType: "running shoes",
        price: 50,
        rating: 4,
        image: "https://essential.vteximg.com.br/arquivos/ids/570243-1000-1000/316-9181_1.jpg?v=637907420039970000",
        description:"Con el Nike Quest 4, la búsqueda de la velocidad continúa. Sal a la calle con elevaciones de espuma más altas y la comodidad amortiguada combinadas con una parte superior ligera que ofrece sujeción segura. Los detalles intuitivos lo convierten en un básico para los corredores habituales.",  
    },
    {
        id: 3,
        name: "Nike Ques 4",
        productType: "running shoes",
        price: 50,
        rating: 4,
        image: "https://essential.vteximg.com.br/arquivos/ids/570203-1000-1000/316-0410_1.jpg?v=637907419849000000",
        description:"¿Te encanta el look clásico del básquetbol retro, pero también te apasiona la cultura acelerada de los partidos actuales? Te presentamos el Nike Court Vision Low. La parte superior texturizada y los revestimientos con costuras se inspiran en el look de tiro de gancho del básquet clásico. El suave cuello de altura media lo mantiene elegante y cómodo.",  
    },
    {
        id:4,
        name: "PUMA COMET 2 ALT",
        productType: "running shoes",
        price: 50,
        rating:4,
        image:"https://essential.vteximg.com.br/arquivos/ids/439431-1000-1000/961-1392_1.jpg?v=637599844472130000",
        description: "Este nuevo desarrollo de la colección invierno trae la combinación de su capellada con tecnología AMORED RUB y tecnología AQUACLEVER.",
    },
    {   id:5,
        name: "Salomon Patrol 40",
        productType: "running shoes",
        price: 50,
        rating:4,
        image:"https://sportline.vtexassets.com/arquivos/ids/628334-1200-auto?v=637911293109970000&width=1200&height=auto&aspect=true",
        description:"Ideal para entrenamientos cómodos, su diseño minimalista y la tecnología Skinnect te aporta el estilo y liviandad que necesitás.",
    },
    {   id:6,
        name: "Salomon Supercross Blast M 43",
        productType: "running shoes",
        price: 50,
        rating:4,
        image:"https://sportline.vtexassets.com/arquivos/ids/605988-1200-auto?v=637820039138670000&width=1200&height=auto&aspect=true",
        description:"Aprovechamos nuestra experiencia en el trail running y aunamos todos los básicos del campo a través: sujeción del pie ajustable, protección y durabilidad.",
    },
    {
        id:7,
        name: "NIKE AIR ZOOM PEGASUS 38 39",
        productType: "running shoes",
        price: 50,
        rating:4,
        image:"https://sportline.vtexassets.com/arquivos/ids/624191-1200-auto?v=637891633962900000&width=1200&height=auto&aspect=true",
        description:"Prepárate para volar en tu caballo de batalla con alas cuenta con una parte posterior con rebote adicional que es perfecta para correr en pavimento.",
    },
    {
        id:8,
        name: "Puma Flyer Flex 39.5",
        productType: "running shoes",
        price: 50,
        rating:4,
        image:"https://sportline.vtexassets.com/arquivos/ids/612268-1200-auto?v=637844069314070000&width=1200&height=auto&aspect=true",
        description:"Las Flyer Flex se presentan con un estilo completamente renovado y una silueta muy audaz.",
    },
    {
        id:9,
        name: "NIKE DOWNSHIFTER 11 43.5",
        productType: "running shoes",
        price: 50,
        rating:4,
        image:"https://sportline.vtexassets.com/arquivos/ids/623501-1200-auto?v=637889930062700000&width=1200&height=auto&aspect=true",
        description: "El Nike Downshifter 11 te brinda un soporte ligero y flexible para que no te detengas mantiene la misma amortiguación suave de la última versión y agrega más soporte alrededor del mediopié.", 
    },

];
export default product